from typing import TypedDict


class GraphState(TypedDict):
    """
    Represents the state of our graph.

    Attributes:
        request: All user request text.
        search_queries: List of search queries to perform.
        knowledge: Knowledge used to generate the blog post.
        post_content: The content of the blog post generated by the model.
        needs_redraft: Whether the post needs to be redrafted.
    """

    request: str = ""
    search_queries: list[str] = []
    knowledge: list[str] = []
    post_content: str = ""
    needs_redraft: bool = False
