from typing import List, TypedDict


class GraphState(TypedDict):
    """
    Represents the state of our graph.

    Attributes:
        topic: The blog post topic.
        knowledge: Knowledge used to generate the blog post.
        post_content: The content of the blog post generated by the model.
    """

    topic: str
    knowledge: List[str]
    post_content: str
